### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by G1K** [Beetle-II/lumi#1]
Может быть добавить под гит package.json и lock вместо node_modules?

**Comment by Beetle-II** [comment]
Пока не получается собрать самостоятельно модуль @abandonware/bluetooth-hci-socket

Вылазит куча зависимостей. Поэтому готовыми модулями.
Да и большинству так проще...

**Comment by G1K** [comment]
Мы можем помочь собрать 
И пакет сформировать чтобы ставить с фида https://openlumi.github.io/openwrt-packages/

**Comment by Toomaaszo** [comment]
I've added `package.json` in my fork and I'm able to prepare `node_modules` directory, directly on gateway. Additional steps that I've done to do that:

- install packages: `gcc python make` 
- call `ar -rc /usr/lib/libpthread.a`
- create `package.json`
- call `npm install` in the project directory

If You want @Beetle-II to cherry pick my changes, I've pushed them on this [branch](https://github.com/Toomaaszo/lumi/tree/integration-with-npm).

**Comment by Beetle-II** [comment]
Добавлено @Toomaaszo.
Сам не проверял.

**Comment by Toomaaszo** [comment]
You could also cherry pick my today [commit](https://github.com/Toomaaszo/lumi/commit/8aa4424d338792424a9a1b127216f9528b241b5f) with additional info in `README.md`.
