### ISSUE TITLE
Проверка длины передаваемого сообщения в lumi/say/set

### ISSUE THREAD

**Issue by MrC0nst** [Beetle-II/lumi#10]
Как выяснилось, у бесплатного Goggle TTS движка есть ограничение на 200 проговариваемых символов. Надо сделать проверку на превышение. Или попробовать разбивать большой текст на несколько мелких отрезков

**Comment by Beetle-II** [comment]
[Поправлено](https://github.com/Beetle-II/lumi/commit/389837d030627787b9056e2e1ca471cd41b3e53c)
