### ISSUE TITLE
Для термомента "MJ_HT_V1" не отображается значение температуры в Homeassistant

### ISSUE THREAD

**Issue by Snakesms** [Beetle-II/lumi#13]
Для термомента "MJ_HT_V1" не отображается значение температуры в Homeassistant из-за неверного формата конфигурационного сообщения.

Для сравнения во влажности:
{"name":"582d34302358_humidity","unique_id":"582d34302358_humidity","device_class":"humidity","state_topic":"lumi/582d34302358","unit_of_measurement":"%","value_template":"{{ value_json.humidity }}","device":{"name":"MJ_HT_V1","identifiers":["MJ_HT_V1"],"sw_version":"1.0","model":"Xiaomi Gateway","manufacturer":"Xiaomi"}}

В температуре:
{"name":"582d34302358_temperature","unique_id":"582d34302358_temperature","device_class":"temperature","state_topic":"lumi/582d34302358","unit_of_measurement":"°C","value_template":"{{ value_json.temperature }}","device":{"identifiers":[null],"sw_version":"1.0","model":"Xiaomi Gateway","manufacturer":"Xiaomi"}}

При добавлении недостающих 
"device":{"name":"MJ_HT_V1","identifiers":["MJ_HT_V1"] к сообщению вручную все работает правильно

П.С. к сожалению поскольку в JS не понимаю ничего то и PR создать нет возможности

**Comment by Beetle-II** [comment]
Поддержка работы BLE больше не поддерживается
