### ISSUE TITLE
Для датчика почвы Xiaomi Flower care не отображается влажность и фертильность почвы

### ISSUE THREAD

**Issue by Snakesms** [Beetle-II/lumi#14]
Для датчика почвы Xiaomi Flower care не отображается влажность и фертильность почвы из-за неверного формата конфигурационного сообщения.

Такое сообщение приходит для влажности:

{"name":"80eaca895950_moisture","unique_id":"80eaca895950_moisture","device_class":"moisture","state_topic":"lumi/80eaca895950","value_template":"{{ value_json.moisture }}","device":{"name":"Flower care","identifiers":["Flower care"],"sw_version":"1.0","model":"Xiaomi Gateway","manufacturer":"Xiaomi"}}

Из него необходимо убрать "device_class":"moisture" (полностью, менять на другойо нет необходимости)
а так же для красоты можно добавить: "icon":"mdi:water-percent"

Для фертильности почвы приходит такое сообщение:

{"name":"80eaca895950_fertility","unique_id":"80eaca895950_fertility","device_class":"fertility","state_topic":"lumi/80eaca895950","value_template":"{{ value_json.fertility }}","device":{"name":"Flower care","identifiers":["Flower care"],"sw_version":"1.0","model":"Xiaomi Gateway","manufacturer":"Xiaomi"}}

Из него необходимо убрать "device_class":"fertility", так же можно добавить:
"icon": "mdi:flower", "unit_of_measurement": "µS/cm"

Заранне спасибо

**Comment by Beetle-II** [comment]
Поддержка работы BLE больше не поддерживается
