### ISSUE TITLE
2 устройства пишут в 1 топик

### ISSUE THREAD

**Issue by nix1am** [Beetle-II/lumi#25]
При наличии 2х устройство в сети и включенной отправкой в HA оба устройства пишут в 1 топик
homeassistant/light/lumi_light
homeassistant/sensor/lumi_illuminance
и тд

**Comment by nix1am** [comment]
В конфете оказывается есть параметр на добавление мака

**Comment by shummo** [comment]
How did u do that? I also have 2 gateway, with different mqtt_topic and topic but i got only 1 device in home assistant.

**Comment by shummo** [comment]
HOw did you do that? I also have 2 gateway, but can't seperate them.
