### ISSUE TITLE
Support for /sys/class/leds/red/brightness instead of backlight

### ISSUE THREAD

**Issue by devbis** [Beetle-II/lumi#4]
OpenWrt for Lumi gateway will migrate to new drivers of LED lights soon.

https://github.com/devbis/openwrt/commit/1a3adc95ccee91cad8766e413cc038cd5fb1b778

The new device paths will be:

/sys/class/leds/red/brightness
/sys/class/leds/green/brightness
/sys/class/leds/blue/brightness

And range 0-255 instead of 0-100. 

Do you plan to add support for this schema in your application? 

Proposal: you can check for the new paths and fallback to the old ones if they are missing

**Comment by Beetle-II** [comment]
Отлично. Так даже проще с яркостью работать...
