### ISSUE TITLE
Использование BLE

### ISSUE THREAD

**Issue by martkotur** [Beetle-II/lumi#7]
Обнаружил неприятные моменты при включении BLE:
1. BLE устройства адски спамят в MQTT. 1-3 сообщения в секунду и пофиг на настройки в конфиге..
2. Начинает течь память на шлюзе со скоростью 20-30Мб в сутки.
Поймал "отвал вайфай при ble". По факту оперативка шлюза была съедена в 0. После чистки запущенных служб отвалов не было. Отключил БТ, утечек памяти не наблюдаю

UPD: После отключения БТ спам пошел от датчика освещенности

**Comment by Beetle-II** [comment]
Поддержка работы BLE больше не поддерживается
