### ISSUE TITLE
Проблемы с проигрыванием файлов в медиаплеере

### ISSUE THREAD

**Issue by MrC0nst** [Beetle-II/lumi#9]
В коде вижу возможную ошибку `url = msg.url.toLowerCase();` Весь текст приводим в нижний регистр.  А файлы могут быть с заглавными буквами.
А вот тут скорее всего вылезают пролемы с пробелами в именах файлов `cp.execSync('mpg123 ' + url);`

**Comment by Beetle-II** [comment]
[Поправлено](https://github.com/Beetle-II/lumi/commit/ef7df6ed6f03e642c4d95370939a788232a9fae5)
